### ISSUE TITLE
Gobinaries finds no tags

### ISSUE THREAD

**Issue by jrs65** [leowzukw/into-ledger#5]
If I follow the instructions in the README for getting an installation via gobinaries.com, it fails with:
```
$ curl -sf https://gobinaries.com/cljoly/into-ledger | sh

  Error: Repository has no tags
```

I think the issue is that the current version tag only has two digits (see https://github.com/tj/gobinaries/issues/29), so this could probably be fixed by renaming that tag to `0.1.0`

**Comment by cljoly** [comment]
Apologies for the delay, I somehow missed your issue.

I’ve added the `0.1.0` tag, that works for me know, feel free to let me know if you encounter other problems. I noticed it was not working when adding the gobinaries.com instructions to the Readme, thought it may be a caching issue and forgot about it. Thanks for letting me know!

**Comment by cljoly** [comment]
Actually, it returns
> Error downloading, got 500 response from server

I will further investigate later.

**Comment by jrs65** [comment]
> Apologies for the delay, I somehow missed your issue.

No worries. Thanks for looking into it!

**Comment by cljoly** [comment]
I ended up uploading a bunch of binaries in the [release page](https://github.com/cljoly/into-ledger/releases/latest). It should be almost as convenient and more reliable.

**Comment by cljoly** [comment]
I’m closing this for now, feel free to comment or open another issue if there is anything else I could help with.

**Comment by jrs65** [comment]
Thanks!
