### ISSUE TITLE
Unfork?

### ISSUE THREAD

**Issue by cljoly** [leowzukw/into-ledger#6]
Remove the forked attribute in github (and update Readme for credits of the original code).

See https://stackoverflow.com/a/29326840

**Comment by bhipple** [comment]
I'd say you should probably unfork.  The upstream project looks pretty dead.

**Comment by cljoly** [comment]
Thanks for your interest in this project!

>  The upstream project looks pretty dead.

I agree with that. But if I unfork, this repo will not be linked to upstream one, which makes it less discoverable. If I may ask, did you find this repo from the upstream's list of fork or by a another way?

**Comment by JensRantil** [comment]
If it helps, I found this project through https://github.com/manishrjain/into-ledger/network.

**Comment by cljoly** [comment]
Thanks @JensRantil. In that case, let's not unfork for now.
